In [3]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [4]:
%%bash
set -e

cd /content

if [ -d smallnet/.git ]; then
    cd smallnet
    git fetch origin
    git pull --ff-only origin main
else
    git clone https://github.com/SepehrAkbari/smallnet.git
fi

Cloning into 'smallnet'...
Updating files: 100% (1635/1635), done.

In [5]:
%cd /content/smallnet
!uv run python scripts/run_experiment.py --help 2>/dev/null || true
!grep -n "cp-iteration-sensitivity" scripts/run_experiment.py

/content/smallnet
usage: run_experiment.py [-h] [--config CONFIG] --stage
                         {cp-iteration-sensitivity,dense,eval-finetuned,finetune,full,profile,rank,reconstruction,reconstruction-figures,structural-zero-shot,validate-data,zero-shot}
                         [--device DEVICE] [--output-dir OUTPUT_DIR]
                         [--max-batches MAX_BATCHES] [--synthetic-smoke]
                         [--ranks RANKS [RANKS ...]]
                         [--seeds SEEDS [SEEDS ...]]
                         [--iteration-budgets ITERATION_BUDGETS [ITERATION_BUDGETS ...]]

Run the reproducible CamVid/VGG16-FCN32s CP diagnostic pipeline.

options:
  -h, --help            show this help message and exit
  --config CONFIG
  --stage {cp-iteration-sensitivity,dense,eval-finetuned,finetune,full,profile,rank,reconstruction,reconstruction-figures,structural-zero-shot,validate-data,zero-shot}
  --device DEVICE       Override config device, e.g. cpu, cuda, mps.
  --output-dir OUTPUT_DIR
                        Override config output_dir.
  --max-batches MAX_BATCHES
                        Optional smoke-test limit for evaluation.
  --synthetic-smoke     Run reconstruction on a small deterministic synthetic
                        Conv2d without CamVid or a checkpoint.
  --ranks RANKS [RANKS ...]
                        Optional reconstruction/structural rank subset.
  --seeds SEEDS [SEEDS ...]
                        Optional reconstruction/structural CP seed subset.
  --iteration-budgets ITERATION_BUDGETS [ITERATION_BUDGETS ...]
                        Optional CP iteration-budget subset for the
                        sensitivity stage.
43:    "cp-iteration-sensitivity": [run_cp_iteration_sensitivity],
86:        if args.stage == "cp-iteration-sensitivity"
94:        if args.stage != "cp-iteration-sensitivity":
95:            raise ValueError("--iteration-budgets is supported only with --stage cp-iteration-sensitivity")
100:        if args.stage not in {"reconstruction", "cp-iteration-sensitivity"}:
103:                "cp-iteration-sensitivity"

In [6]:
!mkdir -p /content/smallnet/model

!rsync -a \
  /content/drive/MyDrive/model/ \
  /content/smallnet/model/

In [7]:
!ls -lh model/best_model.pth
!sha256sum model/best_model.pth

-rw------- 1 root root 513M May 21 16:33 model/best_model.pth
1576b92ebb359a519d57d489f8ee823c033588fbd7c77b1c9091606f42fb74a3  model/best_model.pth

In [8]:
!mkdir -p results/camvid_vgg_cp
!mkdir -p results/paper

!rsync -a \
  /content/drive/MyDrive/smallnet_colab_backup/camvid_vgg_cp/ \
  results/camvid_vgg_cp/

!rsync -a \
  /content/drive/MyDrive/smallnet_colab_backup/paper/ \
  results/paper/

In [9]:
!ls -lh results/camvid_vgg_cp/reconstruction_summary.csv
!ls -lh results/camvid_vgg_cp/reconstruction_metadata.json

-rw------- 1 root root 9.4K Jul 21 19:09 results/camvid_vgg_cp/reconstruction_summary.csv
-rw------- 1 root root 278K Jul 21 19:09 results/camvid_vgg_cp/reconstruction_metadata.json

In [10]:
!pip install -q uv
!uv sync

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.9/26.9 MB 104.1 MB/s eta 0:00:0000:0100:01
Resolved 85 packages in 0.98ms
Checked 79 packages in 1ms

In [11]:
!nvidia-smi

import torch

print("CUDA available:", torch.cuda.is_available())
print(
    "GPU:",
    torch.cuda.get_device_name(0)
    if torch.cuda.is_available()
    else "None",
)

Wed Jul 22 15:57:58 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8             12W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
CUDA available: True
GPU: Tesla T4

In [12]:
import pandas as pd

recon = pd.read_csv(
    "results/camvid_vgg_cp/reconstruction_summary.csv"
)

recon["rank"] = pd.to_numeric(
    recon["rank"], errors="coerce"
)
recon["seed"] = pd.to_numeric(
    recon["seed"], errors="coerce"
)

required = recon[
    (recon["method"] == "cp")
    & (recon["status"] == "completed")
    & (recon["rank"].isin([128, 256, 512]))
]

counts = (
    required.groupby("rank")["seed"]
    .nunique()
    .sort_index()
)

print(counts)

assert counts.to_dict() == {
    128.0: 3,
    256.0: 3,
    512.0: 3,
}

print("Canonical reconstruction rows restored correctly.")

rank
128    3
256    3
512    3
Name: seed, dtype: int64
Canonical reconstruction rows restored correctly.

In [13]:
!uv run python scripts/run_experiment.py \
  --config configs/camvid_vgg_cp_paper.json \
  --stage cp-iteration-sensitivity \
  --device cuda \
  --ranks 128 \
  --seeds 0 1 2 \
  --iteration-budgets 10

Wrote:
  /content/smallnet/results/camvid_vgg_cp/cp_iteration_sensitivity_metadata.json

In [14]:
sensitivity = pd.read_csv(
    "results/camvid_vgg_cp/"
    "cp_iteration_sensitivity_summary.csv"
)

display(
    sensitivity.sort_values(
        ["rank", "iteration_budget", "seed"]
    )
)

,absolute_squared_residual_reduction_10_to_25,absolute_squared_residual_reduction_25_to_50,absolute_squared_residual_reduction_50_to_100,actual_fit_initialization_hash_sha256,actual_relative_frobenius_error,actual_relative_squared_frobenius_error,bound_tolerance,checkpoint_sha256,completed_requested_budget,compression_factor,...,mttkrp_max_explicit_bytes,mttkrp_rank_chunk_size,numerical_precision,output_mode_svd_residual_squared,parameter_count,parameter_ratio,rank,relative_squared_residual_reduction_10_to_100,seed,status
0,NaN,NaN,NaN,274b541906bb26d138a3c296c358a1f53d967259b3d519...,0.950907,0.904225,0.00001,1576b92ebb359a519d57d489f8ee823c033588fbd7c77b...,True,172.470032,...,536870912,64,torch.float32,0.732315,595840,0.005798,128,NaN,0,completed
1,NaN,NaN,NaN,b9afce6ac8279d29cda9e0774bb0ad0ed673aea24c2bc6...,0.950763,0.903951,0.00001,1576b92ebb359a519d57d489f8ee823c033588fbd7c77b...,True,172.470032,...,536870912,64,torch.float32,0.732315,595840,0.005798,128,NaN,1,completed
2,NaN,NaN,NaN,bc0127a02ca75f36109fa2a633ad12f3c55584584e1ce0...,0.950854,0.904122,0.00001,1576b92ebb359a519d57d489f8ee823c033588fbd7c77b...,True,172.470032,...,536870912,64,torch.float32,0.732315,595840,0.005798,128,NaN,2,completed

In [15]:
!rsync -a \
  /content/smallnet/results/camvid_vgg_cp/ \
  /content/drive/MyDrive/smallnet_colab_backup/camvid_vgg_cp/

!rsync -a \
  /content/smallnet/results/paper/ \
  /content/drive/MyDrive/smallnet_colab_backup/paper/

## Experiment

In [16]:
import subprocess
from pathlib import Path

REPO = Path("/content/smallnet")
BACKUP = Path("/content/drive/MyDrive/smallnet_colab_backup")

(BACKUP / "camvid_vgg_cp").mkdir(parents=True, exist_ok=True)
(BACKUP / "paper").mkdir(parents=True, exist_ok=True)

def backup_results():
    subprocess.run(
        [
            "rsync", "-a",
            f"{REPO}/results/camvid_vgg_cp/",
            f"{BACKUP}/camvid_vgg_cp/",
        ],
        check=True,
    )
    subprocess.run(
        [
            "rsync", "-a",
            f"{REPO}/results/paper/",
            f"{BACKUP}/paper/",
        ],
        check=True,
    )
    print("Results backed up to Google Drive.")

def run_sensitivity(rank: int, budget: int):
    command = [
        "uv", "run", "python", "scripts/run_experiment.py",
        "--config", "configs/camvid_vgg_cp_paper.json",
        "--stage", "cp-iteration-sensitivity",
        "--device", "cuda",
        "--ranks", str(rank),
        "--seeds", "0", "1", "2",
        "--iteration-budgets", str(budget),
    ]

    print(f"Running rank={rank}, budget={budget}")

    try:
        subprocess.run(command, cwd=REPO, check=True)
    finally:
        # Also preserve partial rows if the command raises a normal error.
        backup_results()

In [17]:
for budget in [10, 25, 50, 100]:
    run_sensitivity(rank=128, budget=budget)

Running rank=128, budget=10
Results backed up to Google Drive.
Running rank=128, budget=25
Results backed up to Google Drive.
Running rank=128, budget=50
Results backed up to Google Drive.
Running rank=128, budget=100
Results backed up to Google Drive.

In [18]:
sensitivity = pd.read_csv(
    "results/camvid_vgg_cp/cp_iteration_sensitivity_summary.csv"
)

sensitivity["rank"] = pd.to_numeric(
    sensitivity["rank"], errors="coerce"
)
sensitivity["seed"] = pd.to_numeric(
    sensitivity["seed"], errors="coerce"
)
sensitivity["iteration_budget"] = pd.to_numeric(
    sensitivity["iteration_budget"], errors="coerce"
)

display(
    sensitivity[
        sensitivity["rank"] == 128
    ].sort_values(["iteration_budget", "seed"])
)

,absolute_squared_residual_reduction_10_to_25,absolute_squared_residual_reduction_25_to_50,absolute_squared_residual_reduction_50_to_100,actual_fit_initialization_hash_sha256,actual_relative_frobenius_error,actual_relative_squared_frobenius_error,bound_tolerance,checkpoint_sha256,completed_requested_budget,compression_factor,...,mttkrp_max_explicit_bytes,mttkrp_rank_chunk_size,numerical_precision,output_mode_svd_residual_squared,parameter_count,parameter_ratio,rank,relative_squared_residual_reduction_10_to_100,seed,status
0,0.006029,0.002798,0.001891,274b541906bb26d138a3c296c358a1f53d967259b3d519...,0.950907,0.904225,0.00001,1576b92ebb359a519d57d489f8ee823c033588fbd7c77b...,True,172.470032,...,536870912,64,torch.float32,0.732315,595840,0.005798,128,0.011853,0,completed
4,0.005731,0.002912,0.001944,b9afce6ac8279d29cda9e0774bb0ad0ed673aea24c2bc6...,0.950763,0.903951,0.00001,1576b92ebb359a519d57d489f8ee823c033588fbd7c77b...,True,172.470032,...,536870912,64,torch.float32,0.732315,595840,0.005798,128,0.011712,1,completed
8,0.006091,0.003002,0.001943,bc0127a02ca75f36109fa2a633ad12f3c55584584e1ce0...,0.950854,0.904122,0.00001,1576b92ebb359a519d57d489f8ee823c033588fbd7c77b...,True,172.470032,...,536870912,64,torch.float32,0.732315,595840,0.005798,128,0.012207,2,completed
1,0.006029,0.002798,0.001891,274b541906bb26d138a3c296c358a1f53d967259b3d519...,0.947732,0.898196,0.00001,1576b92ebb359a519d57d489f8ee823c033588fbd7c77b...,True,172.470032,...,536870912,64,torch.float32,0.732315,595840,0.005798,128,0.011853,0,completed
5,0.005731,0.002912,0.001944,b9afce6ac8279d29cda9e0774bb0ad0ed673aea24c2bc6...,0.947745,0.898220,0.00001,1576b92ebb359a519d57d489f8ee823c033588fbd7c77b...,True,172.470032,...,536870912,64,torch.float32,0.732315,595840,0.005798,128,0.011712,1,completed
9,0.006091,0.003002,0.001943,bc0127a02ca75f36109fa2a633ad12f3c55584584e1ce0...,0.947645,0.898031,0.00001,1576b92ebb359a519d57d489f8ee823c033588fbd7c77b...,True,172.470032,...,536870912,64,torch.float32,0.732315,595840,0.005798,128,0.012207,2,completed
2,0.006029,0.002798,0.001891,274b541906bb26d138a3c296c358a1f53d967259b3d519...,0.946255,0.895398,0.00001,1576b92ebb359a519d57d489f8ee823c033588fbd7c77b...,True,172.470032,...,536870912,64,torch.float32,0.732315,595840,0.005798,128,0.011853,0,completed
6,0.005731,0.002912,0.001944,b9afce6ac8279d29cda9e0774bb0ad0ed673aea24c2bc6...,0.946207,0.895308,0.00001,1576b92ebb359a519d57d489f8ee823c033588fbd7c77b...,True,172.470032,...,536870912,64,torch.float32,0.732315,595840,0.005798,128,0.011712,1,completed
10,0.006091,0.003002,0.001943,bc0127a02ca75f36109fa2a633ad12f3c55584584e1ce0...,0.946060,0.895029,0.00001,1576b92ebb359a519d57d489f8ee823c033588fbd7c77b...,True,172.470032,...,536870912,64,torch.float32,0.732315,595840,0.005798,128,0.012207,2,completed
3,0.006029,0.002798,0.001891,274b541906bb26d138a3c296c358a1f53d967259b3d519...,0.945255,0.893507,0.00001,1576b92ebb359a519d57d489f8ee823c033588fbd7c77b...,True,172.470032,...,536870912,64,torch.float32,0.732315,595840,0.005798,128,0.011853,0,completed
7,0.005731,0.002912,0.001944,b9afce6ac8279d29cda9e0774bb0ad0ed673aea24c2bc6...,0.945179,0.893364,0.00001,1576b92ebb359a519d57d489f8ee823c033588fbd7c77b...,True,172.470032,...,536870912,64,torch.float32,0.732315,595840,0.005798,128,0.011712,1,completed
11,0.006091,0.003002,0.001943,bc0127a02ca75f36109fa2a633ad12f3c55584584e1ce0...,0.945032,0.893086,0.00001,1576b92ebb359a519d57d489f8ee823c033588fbd7c77b...,True,172.470032,...,536870912,64,torch.float32,0.732315,595840,0.005798,128,0.012207,2,completed

In [19]:
for budget in [10, 25, 50, 100]:
    run_sensitivity(rank=256, budget=budget)

Running rank=256, budget=10
Results backed up to Google Drive.
Running rank=256, budget=25
Results backed up to Google Drive.
Running rank=256, budget=50
Results backed up to Google Drive.
Running rank=256, budget=100
Results backed up to Google Drive.

In [20]:
for budget in [10, 25, 50, 100]:
    run_sensitivity(rank=512, budget=budget)

Running rank=512, budget=10
Results backed up to Google Drive.
Running rank=512, budget=25
Results backed up to Google Drive.
Running rank=512, budget=50
Results backed up to Google Drive.
Running rank=512, budget=100
Results backed up to Google Drive.

In [21]:
import json
import pandas as pd
from pathlib import Path

summary_path = Path(
    "results/camvid_vgg_cp/cp_iteration_sensitivity_summary.csv"
)

sensitivity = pd.read_csv(summary_path)

for column in ["rank", "seed", "iteration_budget"]:
    sensitivity[column] = pd.to_numeric(
        sensitivity[column], errors="coerce"
    )

print("Total rows:", len(sensitivity))
print("Status counts:")
print(sensitivity["status"].value_counts(dropna=False))

completed = sensitivity[
    sensitivity["status"] == "completed"
].copy()

print("\nCompleted rows by rank and budget:")
print(
    completed.groupby(
        ["rank", "iteration_budget"]
    )["seed"].nunique()
)

duplicates = completed.duplicated(
    subset=["rank", "seed", "iteration_budget"],
    keep=False,
)

print("\nDuplicate scientific rows:", int(duplicates.sum()))

assert len(completed) == 36
assert not duplicates.any()

expected_ranks = {128, 256, 512}
expected_budgets = {10, 25, 50, 100}

assert set(completed["rank"].astype(int)) == expected_ranks
assert set(completed["iteration_budget"].astype(int)) == expected_budgets

for rank in expected_ranks:
    for budget in expected_budgets:
        subset = completed[
            (completed["rank"] == rank)
            & (completed["iteration_budget"] == budget)
        ]
        assert set(subset["seed"].astype(int)) == {0, 1, 2}

print("\nSensitivity sweep is complete.")

Total rows: 36
Status counts:
status
completed    36
Name: count, dtype: int64

Completed rows by rank and budget:
rank  iteration_budget
128   10                  3
      25                  3
      50                  3
      100                 3
256   10                  3
      25                  3
      50                  3
      100                 3
512   10                  3
      25                  3
      50                  3
      100                 3
Name: seed, dtype: int64

Duplicate scientific rows: 0

Sensitivity sweep is complete.

In [22]:
initialization_counts = (
    completed.groupby(["rank", "seed"])[
        "initialization_hash_sha256"
    ]
    .nunique()
)

print(initialization_counts)

assert (initialization_counts == 1).all()

print("All budgets used matching initial factors within each rank and seed.")

rank  seed
128   0       1
      1       1
      2       1
256   0       1
      1       1
      2       1
512   0       1
      1       1
      2       1
Name: initialization_hash_sha256, dtype: int64
All budgets used matching initial factors within each rank and seed.

In [23]:
with open(
    "results/camvid_vgg_cp/cp_iteration_sensitivity_metadata.json"
) as f:
    metadata = json.load(f)

print("Failures:")
print(metadata.get("failures"))

print("\nAudit complete:")
print(metadata.get("audit_complete"))

print("\nFigure failures:")
print(metadata.get("figure_generation_failures"))

print("\nAudit failures:")
print(metadata.get("audit_generation_failures"))

Failures:
[]

Audit complete:
True

Figure failures:
[]

Audit failures:
[]

In [24]:
reproduction = metadata.get(
    "canonical_ten_iteration_reproduction", []
)

display(pd.DataFrame(reproduction))

assert len(reproduction) == 9
assert all(item.get("available") for item in reproduction)
assert all(item.get("within_tolerance") for item in reproduction)

print("All sensitivity-budget-10 rows reproduce the canonical results.")

,rank,seed,available,sensitivity_squared_residual,canonical_squared_residual,absolute_squared_residual_difference,tolerance,within_tolerance
0,128,0,True,0.904225,0.904225,0.0,0.00001,True
1,128,1,True,0.903951,0.903951,0.0,0.00001,True
2,128,2,True,0.904122,0.904122,0.0,0.00001,True
3,256,0,True,0.864546,0.864546,0.0,0.00001,True
4,256,1,True,0.864516,0.864516,0.0,0.00001,True
5,256,2,True,0.864519,0.864519,0.0,0.00001,True
6,512,0,True,0.807686,0.807686,0.0,0.00001,True
7,512,1,True,0.807842,0.807842,0.0,0.00001,True
8,512,2,True,0.807424,0.807424,0.0,0.00001,True

All sensitivity-budget-10 rows reproduce the canonical results.

In [25]:
audit_path = Path(
    "results/paper/cp_iteration_sensitivity_audit.md"
)

print(audit_path.read_text())

# CP iteration-budget sensitivity audit

Status: **complete**.

This diagnostic reports completed requested budgets and residual stabilization. It does not claim certified convergence because no per-iteration convergence history is available.

## Rank-level diagnostics

| Rank | Budget | Mean squared residual | Population SD | Seed range | Mean gap above bound |
|---:|---:|---:|---:|---:|---:|
| 128 | 10 | 0.904099241 | 0.000113080 | 0.000274071 | 0.171784210 |
| 128 | 25 | 0.898148846 | 0.000083929 | 0.000188989 | 0.165833816 |
| 128 | 50 | 0.895245000 | 0.000156815 | 0.000368376 | 0.162929970 |
| 128 | 100 | 0.893318771 | 0.000174707 | 0.000420873 | 0.161003741 |
| 256 | 10 | 0.864526949 | 0.000013443 | 0.000029993 | 0.204287830 |
| 256 | 25 | 0.855216880 | 0.000012177 | 0.000028228 | 0.194977761 |
| 256 | 50 | 0.850743058 | 0.000066848 | 0.000158042 | 0.190503938 |
| 256 | 100 | 0.847853971 | 0.000097262 | 0.000237770 | 0.187614852 |
| 512 | 10 | 0.807650989 | 0.000172536 | 0.000418184 | 0.254440073 |
| 512 | 25 | 0.793902579 | 0.000110956 | 0.000270456 | 0.240691663 |
| 512 | 50 | 0.787474859 | 0.000080270 | 0.000195451 | 0.234263943 |
| 512 | 100 | 0.783410227 | 0.000108803 | 0.000257702 | 0.230199311 |

## Required descriptive thresholds

- Rank 128: mean 50-to-100 reduction `0.001926229`; less than `1e-3`: `False`. Mean relative 10-to-100 reduction `1.1924%`; less than 1%: `False`. Seed variability `increased`.
- Rank 256: mean 50-to-100 reduction `0.002889086`; less than `1e-3`: `False`. Mean relative 10-to-100 reduction `1.9286%`; less than 1%: `False`. Seed variability `increased`.
- Rank 512: mean 50-to-100 reduction `0.004064632`; less than `1e-3`: `False`. Mean relative 10-to-100 reduction `3.0014%`; less than 1%: `False`. Seed variability `decreased`.
- Rank ordering changed across complete budgets: `False`.

## Canonical ten-iteration reproduction

- rank=128, seed=0: absolute residual difference `0.000e+00`, within tolerance=`True`.
- rank=128, seed=1: absolute residual difference `0.000e+00`, within tolerance=`True`.
- rank=128, seed=2: absolute residual difference `0.000e+00`, within tolerance=`True`.
- rank=256, seed=0: absolute residual difference `0.000e+00`, within tolerance=`True`.
- rank=256, seed=1: absolute residual difference `0.000e+00`, within tolerance=`True`.
- rank=256, seed=2: absolute residual difference `0.000e+00`, within tolerance=`True`.
- rank=512, seed=0: absolute residual difference `0.000e+00`, within tolerance=`True`.
- rank=512, seed=1: absolute residual difference `0.000e+00`, within tolerance=`True`.
- rank=512, seed=2: absolute residual difference `0.000e+00`, within tolerance=`True`.

## Scientific decisions

1. **Is ten iterations near a residual plateau?** `False` under the two requested descriptive checks: all-rank 50-to-100 change below 1e-3=`False` and all-rank absolute relative 10-to-100 change below 1%=`False`. This is residual stabilization, not certified convergence.
2. **Does a larger budget substantially reduce the CP--SVD gap?** At least one rank changes by 1% or more, so budget sensitivity is materially present under the requested diagnostic. The fractions of the ten-iteration gap removed by 100 iterations are rank 128: `6.2756%`, rank 256: `8.1615%`, rank 512: `9.5271%`. These descriptive fractions, rather than a preset conclusion, determine whether the gap reduction is material.
3. **Is the widening high-rank gap present at 100 iterations?** The 100-iteration mean gaps are rank 128: `0.161004`, rank 256: `0.187615`, rank 512: `0.230199`. The gap increases monotonically with rank=`True`; rank ordering changed=`False`.
4. **Does any rank require a larger canonical budget?** Ranks failing at least one requested stabilization check: `[128, 256, 512]`. This is a protocol decision, not a convergence certificate.
5. **Budget for later experiments:** No final common budget is justified yet; extend only ranks whose 50-to-100 change is at least 1e-3, then select a common stabilized budget.
6. **Would a budget change require rerunning canonical zero-shot results?** Yes. Any CP factors used for zero-shot evaluation must be refitted at the selected budget and the corresponding zero-shot rows regenerated. The existing ten-iteration artifacts must remain as a separately labeled protocol.
7. **Is another budget experiment necessary?** No further budget grid is required if the 50-to-100 changes are descriptively negligible for all ranks; otherwise extend only the affected ranks with the same initialization protocol.

In [26]:
rank_summary = pd.read_csv(
    "results/camvid_vgg_cp/"
    "cp_iteration_sensitivity_rank_summary.csv"
)

display(
    rank_summary.sort_values(
        ["rank", "iteration_budget"]
    )
)

,actual_relative_squared_frobenius_error_max,actual_relative_squared_frobenius_error_mean,actual_relative_squared_frobenius_error_min,actual_relative_squared_frobenius_error_seed_range,actual_relative_squared_frobenius_error_std_population,completed_seed_count,expected_seed_count,gap_above_max_bound_mean,iteration_budget,max_unfolding_tail_bound_squared,mean_absolute_squared_residual_reduction_50_to_100,mean_change_50_to_100_less_than_1e_minus_3,mean_relative_reduction_10_to_100_less_than_1_percent,mean_relative_squared_residual_reduction_10_to_100,method,output_mode_svd_residual_squared,rank,seed_range_change_10_to_100,seed_variability_trend_10_to_100
0,0.904225,0.904099,0.903951,0.000274,0.000113,3,3,0.171784,10,0.732315,0.001926,False,False,0.011924,cp,0.732315,128,0.000147,increased
1,0.898220,0.898149,0.898031,0.000189,0.000084,3,3,0.165834,25,0.732315,0.001926,False,False,0.011924,cp,0.732315,128,0.000147,increased
2,0.895398,0.895245,0.895029,0.000368,0.000157,3,3,0.162930,50,0.732315,0.001926,False,False,0.011924,cp,0.732315,128,0.000147,increased
3,0.893507,0.893319,0.893086,0.000421,0.000175,3,3,0.161004,100,0.732315,0.001926,False,False,0.011924,cp,0.732315,128,0.000147,increased
4,0.864546,0.864527,0.864516,0.000030,0.000013,3,3,0.204288,10,0.660239,0.002889,False,False,0.019286,cp,0.660239,256,0.000208,increased
5,0.855234,0.855217,0.855206,0.000028,0.000012,3,3,0.194978,25,0.660239,0.002889,False,False,0.019286,cp,0.660239,256,0.000208,increased
6,0.850834,0.850743,0.850676,0.000158,0.000067,3,3,0.190504,50,0.660239,0.002889,False,False,0.019286,cp,0.660239,256,0.000208,increased
7,0.847977,0.847854,0.847739,0.000238,0.000097,3,3,0.187615,100,0.660239,0.002889,False,False,0.019286,cp,0.660239,256,0.000208,increased
8,0.807842,0.807651,0.807424,0.000418,0.000173,3,3,0.254440,10,0.553211,0.004065,False,False,0.030014,cp,0.553211,512,-0.000160,decreased
9,0.794046,0.793903,0.793775,0.000270,0.000111,3,3,0.240692,25,0.553211,0.004065,False,False,0.030014,cp,0.553211,512,-0.000160,decreased
10,0.787566,0.787475,0.787371,0.000195,0.000080,3,3,0.234264,50,0.553211,0.004065,False,False,0.030014,cp,0.553211,512,-0.000160,decreased
11,0.783519,0.783410,0.783262,0.000258,0.000109,3,3,0.230199,100,0.553211,0.004065,False,False,0.030014,cp,0.553211,512,-0.000160,decreased

In [27]:
!ls -lh results/paper/figures/cp_iteration_sensitivity.*

-rw-r--r-- 1 root root 2.8K Jul 22 16:08 results/paper/figures/cp_iteration_sensitivity.csv
-rw-r--r-- 1 root root  22K Jul 22 16:08 results/paper/figures/cp_iteration_sensitivity.pdf
-rw-r--r-- 1 root root 186K Jul 22 16:08 results/paper/figures/cp_iteration_sensitivity.png

In [28]:
backup_results()

Results backed up to Google Drive.

In [29]:
!cd /content/smallnet && \
  zip -r /content/smallnet_cp_iteration_sensitivity_results.zip \
  results/camvid_vgg_cp/cp_iteration_sensitivity_summary.csv \
  results/camvid_vgg_cp/cp_iteration_sensitivity_rank_summary.csv \
  results/camvid_vgg_cp/cp_iteration_sensitivity_metadata.json \
  results/camvid_vgg_cp/cp_iteration_sensitivity_config_used.json \
  results/paper/cp_iteration_sensitivity_audit.md \
  results/paper/figures/cp_iteration_sensitivity.csv \
  results/paper/figures/cp_iteration_sensitivity.pdf \
  results/paper/figures/cp_iteration_sensitivity.png

  adding: results/camvid_vgg_cp/cp_iteration_sensitivity_summary.csv (deflated 89%)
  adding: results/camvid_vgg_cp/cp_iteration_sensitivity_rank_summary.csv (deflated 68%)
  adding: results/camvid_vgg_cp/cp_iteration_sensitivity_metadata.json (deflated 71%)
  adding: results/camvid_vgg_cp/cp_iteration_sensitivity_config_used.json (deflated 68%)
  adding: results/paper/cp_iteration_sensitivity_audit.md (deflated 63%)
  adding: results/paper/figures/cp_iteration_sensitivity.csv (deflated 68%)
  adding: results/paper/figures/cp_iteration_sensitivity.pdf (deflated 38%)
  adding: results/paper/figures/cp_iteration_sensitivity.png (deflated 18%)

In [30]:
!cp /content/smallnet_cp_iteration_sensitivity_results.zip \
  /content/drive/MyDrive/smallnet_colab_backup/